CREATE TABLE PUBLIC.events (
	id TEXT PRIMARY KEY,
	cms_id VARCHAR(64) UNIQUE NOT NULL,
	title TEXT NOT NULL,
	description TEXT,
	message TEXT NOT NULL,
	date TIMESTAMP NOT NULL,
	at_peine_perdue BOOLEAN);

CREATE TABLE PUBLIC.pictures (
	id TEXT PRIMARY KEY,
	url TEXT NOT NULL,
	width INTEGER,
	height INTEGER,
	event_id TEXT REFERENCES events(id) ON DELETE CASCADE);