CREATE TABLE users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created TIMESTAMP,
    last_connection TIMESTAMP
);

CREATE TABLE connection_tokens (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value TEXT,
    expires TIMESTAMP,
		user_id INTEGER NOT NULL,
    CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
